% Script generated by Brainstorm (07-Sep-2021)

% Input files
sFiles = {...
    'Subject01/@rawtutorial_eeg/data_0raw_tutorial_eeg.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: DC offset correction: [All file]
sFiles = bst_process('CallProcess', 'process_baseline', sFiles, [], ...
    'baseline',    [], ...
    'sensortypes', 'MEG, EEG', ...
    'method',      'bl', ...  % DC offset correction:    x_std = x - &mu;
    'read_all',    1);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);

