% Script generated by Brainstorm (07-Sep-2021)

% Input files
sFiles = {...
    'Subject01/@rawtutorial_eeg_bl_band/data_0raw_tutorial_eeg_bl_band.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: Interpolate bad electrodes
sFiles = bst_process('CallProcess', 'process_eeg_interpbad', sFiles, [], ...
    'maxdist',     5, ...
    'sensortypes', 'EEG');

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);

