%Parameter=load('/udd/nforde/Nina/StageEEGpre/data/RAWformat_Test4_results/project_state.mat')



addAutomagicPaths();

name = 'script_projecthbn';
dataFolder = '/home/Data/NDARAC462DZH_resting/EEG/raw';
resultsFolder = '/home/Data/NDARAC462DZH_resting/EEG/results_script';
ext = '.mat';

Params= struct('FilterParams',         struct('high',  struct('freq',  0.1000, 'order', []),... % Default order for filtering
                                               'low',   struct('freq',  35, 'order', [])),...
                 'CRDParams',        struct([]),...
                 'PrepParams',          struct('lineFrequencies', 50), ...
                 'HighvarParams',       struct('sd', 25,...
                                                'cutoff', 100, ...
                                                'rejRatio', 0.5000), ...
                 'MinvarParams',       struct('sd', 1),...
                 'InterpolationParams', struct('method', 'spherical'), ...
                 'ICLabelParams',       struct([]),...
                'EEGSystem',           struct('name', 'EGI',...
                                               'sys10_20', 0, ...
                                               'locFile', '', ...
                                               'refChan', struct('idx', []), ...
                                               'fileLocType', '',...
                                               'eogChans', [], ...
                                               'tobeExcludedChans', []), ...
                 'Settings',            struct('trackAllSteps', 1, ...
                                               'pathToSteps', '/allSteps.mat',...
                                               'colormap','Default',...
                                               'sortChans', 0)...
                 );
       

sRate= [];
VisualisationParams = struct();





% Template for all the parameters

              
                                              
project = Project(name, dataFolder, resultsFolder, ext, Params, VisualisationParams,sRate);
project.preprocessAll();
%project.interpolateSelected();