%Parameter=load('/udd/nforde/Nina/StageEEGpre/data/RAWformat_Test4_results/project_state.mat')
restoredefaultpath;
clear all; 
clc; %First, clean the environment

addpath( '/home/nforde/Documents/StageEEGpre/dependencies/automagic-master');


addAutomagicPaths();

name = '24janv2';
dataFolder = '/home/nforde/Documents/StageEEGpre/data/formatBIDS';
resultsFolder = '/home/nforde/Documents/StageEEGpre/data/formatBIDS_24janv_results2';
ext = '.dat';

% Params= struct('FilterParams',         struct('high',  struct('freq',  0.1000, 'order', []),... % Default order for filtering
%                                                'low',   struct('freq',  35, 'order', [])),...
%                  'CRDParams',        struct([]),...
%                  'PrepParams',          struct('lineFrequencies', 50), ...
%                  'HighvarParams',       struct('sd', 25,...
%                                                 'cutoff', 100, ...
%                                                 'rejRatio', 0.5000), ...
%                  'MinvarParams',       struct('sd', 1),...
%                  'InterpolationParams', struct('method', 'spherical'), ...
%                  'ICLabelParams',       struct([]),...
%                 'EEGSystem',           struct('name', 'EGI',...
%                                                'sys10_20', 0, ...
%                                                'locFile', '', ...
%                                                'refChan', struct('idx', []), ...
%                                                'fileLocType', '',...
%                                                'eogChans', [], ...
%                                                'tobeExcludedChans', []), ...
%                  'Settings',            struct('trackAllSteps', 1, ...
%                                                'pathToSteps', '/allSteps.mat',...
%                                                'colormap','Default',...
%                                                'sortChans', 0)...
%                  );
       
Params=load('/home/nforde/Documents/StageEEGpre/data/formatBIDS_24janv_results2/project_state.mat');
Params=Params.self.params;
sRate= [];
VisualisationParams = struct();





% Template for all the parameters

              
                                              
project = Project(name, dataFolder, resultsFolder, ext, Params, VisualisationParams,sRate);
project.preprocessAll();
%project.interpolateSelected();